import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {fetchEntries} from '../lib/api'
import Gallery from '../components/Gallery'
import Layout from '../components/Layout'
import { FC } from 'react'
import { IPhotoGallery } from '../@types/generated/contentful'

interface IHome {
  photoGallery: IPhotoGallery
}

const Home: FC<IHome> = ({photoGallery}) => {
  const images = photoGallery.fields.images;
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>
        {images && <Gallery imageArray={images} />}
      </div>
    </Layout>
  )
}

export default Home;


const PHOTO_GALLERY_ID = "photoGallery";
export const getStaticProps: GetStaticProps = async () => {
  const photoGallery = await fetchEntries({content_type: PHOTO_GALLERY_ID})
  if (!photoGallery) {
    console.error("photogallery not available")
    return {
      props: {}
    }
  }
  return {
    props: {
      photoGallery: photoGallery[0]
    }
  }
}
