import type { GetStaticProps } from "next";
import Head from "next/head";
import { fetchEntries } from "../lib/api";
import Gallery from "../components/Gallery/Gallery";
import Layout from "../components/_Layout/Layout";

// typeImports
import { FC } from "react";
import { IPhotoGallery } from "../@types/generated/contentful";

// styleImports
import styles from "../styles/Home.module.css";
import { Icon } from "../components/Icon/Icon";

interface IHome {
  photoGallery: IPhotoGallery;
}

const Home: FC<IHome> = ({ photoGallery }) => {
  const images = photoGallery.fields.images;
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>Photography</h1>
        <h3>by Thomas Bieniek</h3>
        <p>
          <a href="#">show me a link</a>
        </p>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas vel
          tempore laborum mollitia quia quo qui doloremque pariatur? Voluptatem
          at ullam maxime ex veritatis sint esse dolor ipsum itaque quis? Lorem
          ipsum dolor sit amet consectetur adipisicing elit. Quam obcaecati quas
          dolor? Eligendi perspiciatis eius obcaecati ipsum fugit, cupiditate
          amet quos eum quam laborum illum dignissimos repudiandae, nostrum,
          voluptate nulla.
        </p>
        <Icon iconName="done" hoverAnimation />
        {images && <Gallery imageArray={images} />}
      </div>
    </Layout>
  );
};

export default Home;

const PHOTO_GALLERY_ID = "photoGallery";
export const getStaticProps: GetStaticProps = async () => {
  const photoGallery = await fetchEntries({ content_type: PHOTO_GALLERY_ID });
  if (!photoGallery) {
    console.error("photogallery not available");
    return {
      props: {},
    };
  }
  return {
    props: {
      photoGallery: photoGallery[0],
    },
  };
};
