import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {fetchEntries} from '../lib/api'
import Gallery from '../components/Gallery'

const PHOTO_GALLERY_ID = "photoGallery";

export const getStaticProps: GetStaticProps = async () => {
  const photoGallery = await fetchEntries({content_type: PHOTO_GALLERY_ID})
  return {
    props: {
      photoGallery
    }
  }
}

const Home: NextPage<GetStaticProps> = (props) => {
  const photoGallery = props.photoGallery[0]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Gallery imageArray={photoGallery.fields.images} />
      
    </div>
  )
}

export default Home
